### ISSUE TITLE
Errors when building

### ISSUE THREAD

**Issue by damianesteban** [kickstarter/ios-oss#10]
Thank you so much for open-sourcing this project...there seems to be a wealth of truly fantastic code and I can't wait to really dive in.

Unfortunately when I try to build the application I get the following error:

`.../Library/ViewModels/EmptyStatesViewModel.swift:1:8: No such module 'KsApi'`

Am I missing something?

Thank you.

**Comment by mbrandonw** [comment]
Oh hey, were you able to resolve this?

**Comment by damianesteban** [comment]
Yes I was.  Thank you :)

**Comment by mbrandonw** [comment]
Are you using Xcode 7.3.1?

We are kinda slacking on our swift 2.3 / Xcode 8 support...

**Comment by damianesteban** [comment]
I'm most definitely not using Xcode 7.3.1.  I apologize.  I think I may install 7.3.1 just to work with this project 👍  Thanks.
