### ISSUE TITLE
Looking to contribute

### ISSUE THREAD

**Issue by nishant2718** [kickstarter/ios-oss#1064]
Hey kickstarter - iOS team!

I'm looking to contribute but am not sure where to start. The projects board is empty & there aren't any bugs, small user stories, "help wanted" issues filed. Can I assume that all that is tracked somewhere outside of Github? If so, Is is publicly accessible?

Thanks in advance!
Nishant

**Comment by justinswart** [comment]
Hi @nishant2718! While we appreciate your wanting to contribute, this is not really something we currently support in our product development process. As mentioned in our [README.md](README.md):

> We intend for this project to be an educational resource: we are excited to share our wins, mistakes, and methodology of iOS development as we work in the open. Our primary focus is to continue improving the app for our users in line with our roadmap.

If that ever changes, we'll let you know!

Of course if you do find a bug using the app or notice something that you think could be improved, open an issue to discuss it and we could potentially help shepherd a PR into the codebase. [This issue](https://github.com/kickstarter/ios-oss/issues/949) is an example of a time we've done that before.
