### ISSUE TITLE
Compile time error ?

### ISSUE THREAD

**Issue by tariq235** [kickstarter/ios-oss#108]
I have cloned the repo as per the given instructions - 

Clone this repository.
Run make bootstrap to install tools and dependencies.
Run make test-all to build and run tests on all platforms.

But I am getting error when i try to compile the project. See screenshot
![screen shot 2017-03-14 at 4 35 34 pm](https://cloud.githubusercontent.com/assets/349211/23892184/87a81cac-08d4-11e7-8666-0280ef7e2809.png)

**Comment by mbrandonw** [comment]
Hi, what version of xcode are ya using?

**Comment by tariq235** [comment]
I'm on Version 8.2.1
Well by changing "Enable Bitcode" from yes to no in ReactiveSwift-iOS target solved the problem. I'm not sure whether this is correct or not.

**Comment by mbrandonw** [comment]
yeah not sure what is going on. it seems to work for us without doing that, and it builds on circleci too.

gonna close this for now. glad something worked for ya!
