### ISSUE TITLE
Cannot run app in simulator - None of the apis are hitting. How to contribute ?

### ISSUE THREAD

**Issue by tariq235** [kickstarter/ios-oss#109]
How can we contribute to the project when none of the apis are working ?
Can someone please help how to run app in simulator ? Currently all screens are white.

**Comment by shine15** [comment]
@tariq235 set KsApi.Secrets.isOSS = true, use mock data.

**Comment by mbrandonw** [comment]
what @shine15 said, but also i believe that should be the default behavior when running the OSS code. please let us know if that is not the case.

we don't allow the OSS code to hit our public API, and instead provide a mock version that serves up hard coded data immediately.

**Comment by priteshshah1983** [comment]
It took me a few minutes to figure out that you have to change `public static let isOSS = false` to `public static let isOSS = true` by modifying `Secrets.swift` under `Configs` group within Xcode.
