### ISSUE TITLE
build "no such module 'Argo'" on fresh setup

### ISSUE THREAD

**Issue by SeanFelipe** [kickstarter/ios-oss#1101]
Hello Kickstarters,

I just attempted a build from a fresh clone and `make bootstrap`, and the compiler threw an error No such module 'Argo' . I next tried a `carthage update`, and saw some output which seemed to download dependencies, but still seeing the error. Finally I edited the Framework Search Paths to contain `${PROJECT_DIR}/Carthage/Contents` and tried again, but same error.

I'm probably doing something stupid but I'm more of an Android hack than ios.

Anyhow ... any suggestions ? I hope I followed your install directions properly plus trying some of my own stuffs.

<img width="293" alt="Screen Shot 2020-03-08 at 9 35 47 PM" src="https://user-images.githubusercontent.com/5632981/76183714-a467cf00-6186-11ea-81aa-ddcebc52bb9b.png">

**Comment by justinswart** [comment]
Did you notice any errors during `make bootstrap`? Which version of Xcode are you using?

**Comment by SeanFelipe** [comment]
Using Xcode 11.2

I don't remember any errors but I can try again. I do see a link warning upon subsequent runs of `make bootstrap`, but when I `brew link carthage` it says already linked. Maybe this has something to do with it ?

```
12:59 $ make bootstrap
set -o pipefail; bin/carthage.sh;
Unlinking /usr/local/Cellar/carthage/0.33.0... 4 symlinks removed
######################################################################## 100.0%##O=#  #                 ######################################################################## 100.0%
Warning: carthage 0.33.0 is already installed, it's just not linked
You can use `brew link carthage` to link this version.
```

let me try cleaning and bootstrapping again.

**Comment by SeanFelipe** [comment]
How to clean the bootstrap phase ? `make clean` gives me a simulator error "requested device could not be found". Thanks !

**Comment by justinswart** [comment]
🤔  Try `rm -rf Carthage`, install Xcode 11.3.1 and run `make dependencies` again.

**Comment by SeanFelipe** [comment]
Okay, I ran `make bootstrap` and I see the following output. Looks like I may have an older version of Swift; maybe this is fixed with an Xcode update ? I'll try `make dependencies` first then try and Xcode update .

```
✔ ~/p/Kickstarter/ios-oss [master|✚ 10] 
08:02 $ make bootstrap
set -o pipefail; bin/carthage.sh;
Unlinking /usr/local/Cellar/carthage/0.33.0... 4 symlinks removed
######################################################################## 100.0%
Warning: carthage 0.33.0 is already installed, it's just not linked
You can use `brew link carthage` to link this version.
Cleaning /usr/local/Cellar/carthage/0.33.0
4 links created for /usr/local/Cellar/carthage/0.33.0
Updating dependencies
Please update to the latest Carthage version: 0.34.0. You currently are on 0.33.0
*** Fetching swift-sdk
*** Fetching stripe-ios
*** Fetching ReactiveSwift
*** Fetching ios-snapshot-test-case
*** Fetching facebook-objc-sdk
*** Fetching appcenter-sdk-apple
*** Downloading binary-only framework Qualtrics at "https://s3-us-west-2.amazonaws.com/si-mobile-sdks/ios/Qualtrics.json"
*** Fetching Alamofire
*** Fetching Runes
*** Checking out Alamofire at "5.0.2"
*** Checking out ReactiveSwift at "6.1.0"
*** Checking out stripe-ios at "v18.0.0"
*** Checking out Argo at "39f06f089d25c111444e5a85eef64586e54756ac"
*** Checking out Curry at "b6bf27ec9d711f607a8c7da9ca69ee9eaa201a22"
*** Checking out facebook-objc-sdk at "v5.0.2"
*** Checking out Kickstarter-Prelude at "9118beee2b37fa5fc5a4f56502c1fa99030b9f9e"
*** Checking out swift-sdk at "v3.1.0"
*** Checking out ios-snapshot-test-case at "6.2.0"
*** Checking out AlamofireImage at "8e635e6151212f8871a321bbdd980af7c31af73b"
*** Checking out Kickstarter-ReactiveExtensions at "48a3f507995a6bdae964ddf9f2347af6bf74a19f"
*** Checking out appcenter-sdk-apple at "2.5.0"
*** Checking out Runes at "v4.2.2"
*** Downloading appcenter-sdk-apple.framework binary at "2.5.0"
*** Downloading facebook-objc-sdk.framework binary at "Facebook SDK v5.0.2"
*** Downloading ios-snapshot-test-case.framework binary at "6.2.0"
*** xcodebuild output can be found in /var/folders/08/psnnwkq92ngc_nk1549bs3wr0000gp/T/carthage-xcodebuild.fQbcCa.log
*** Downloading binary-only framework Qualtrics at "https://s3-us-west-2.amazonaws.com/si-mobile-sdks/ios/Qualtrics.json"
Incompatible Swift version - framework was built with 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15) and the local version is 5.1.2 (swiftlang-1100.0.278 clang-1100.0.33.9).
(Skipping secrets.)
if [ ! -d Frameworks/native-secrets ]; \
	then \
		mkdir -p Frameworks/native-secrets/ios \
		&& cp -n Configs/Secrets.swift.example Frameworks/native-secrets/ios/Secrets.swift \
		|| true; \
	fi
```

**Comment by SeanFelipe** [comment]
Okay similar Swift version error with `make dependencies` so let me update Xcode and hopefully that resolves my Swift problem.

**Comment by SeanFelipe** [comment]
all right, updating xcode, removing the Carthage folder and re-running `make bootstrap` ... Build Succeeded !

Thanks for bearing with me :)
