### ISSUE TITLE
Playgrounds no longer working after migration?

### ISSUE THREAD

**Issue by tkohout** [kickstarter/ios-oss#118]
Hello!
first of all I want to thank you guys for open sourcing your code, it's always awesome to learn from code of other app developers.

I noticed that the playgrounds are not yet migrated to the swift 3. Is it because they don't work so well under the xcode 8.x or you just didn't get around to it?

The reason I ask is that we got excited about the possibilities of playground driven development and tried it out in project of our own. But when the project got larger the playgrounds were starting very slow and they often crash under mysterious circumstances. E.g. it runs on every third attempt, otherwise it crash on `pthread_rwlock_rdlock failed` and others. Did you also encounter those issues?

When I try to migrate and run any of your playgrounds in Xcode 8.2.1 i get errors like this:

```
Playground execution failed: error: Couldn't lookup symbols:
  __TMaC21Kickstarter_Framework13RootViewModel
```

when trying to use anything that's inside the Kickstarter framework.

Thanks
Tomas

**Comment by mbrandonw** [comment]
Yeah, we've also been having a lot of troubles with playgrounds in Xcode 8.x :/ It's the main reason we haven't converted all of the playgrounds to proper Swift 3 syntax.

However, Xcode 8.3 beta seems to have fixed most of the issues we were seeing. We no longer see the `pthread_rwlock_rdlock` problem from the little bit of testing we have done so far. Playgrounds are still a bit slow, but it's better than nothing.

I will say that playgrounds worked quite well in Xcode 7. We used em for _everything_, pretty much forgoing the simulator entirely in favor of playgrounds.

Hopefully it will get better soon, but it's still a little scary how fragile playgrounds have been for app development.

**Comment by tkohout** [comment]
Thanks for the info. The Xcode 8.3 works quite well in our projects. I migrated the playgrounds while I was at it https://github.com/kickstarter/ios-oss/pull/121
