### ISSUE TITLE
No such module 'Argo'

### ISSUE THREAD

**Issue by litianurazvan** [kickstarter/ios-oss#1231]
Hi,

I tried cloning the project, run `make bootstrap` and opened the project with Xcode 11.5. When compiling I get `No such module 'Argo'` in `ActivityEnvelope.swift` file. I am not sure what I am doing wrong.

**Comment by justinswart** [comment]
hi @litianurazvan, what was the console output when you ran `make bootstrap`? Usually the `No such module 'Argo'` error points to a failure during building the dependencies.

Try running `carthage bootstrap --platform iOS` and look out for any build errors.

Also make sure that your command line tools are also set to use Xcode 11.5.

**Comment by AbdulAli** [comment]
Incompatible Swift version - framework was built with 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29) and the local version is 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15).

I removed the carthage cache and updated it. Still getting the same error on the build.
