### ISSUE TITLE
No such module ‘AppCenter'

### ISSUE THREAD

**Issue by LeoWang0219** [kickstarter/ios-oss#1232]
1,Many '.framework' files are missing, for example：AppCenter.framework,   Argo.framework,  Curry.framework ........(third part .framework) ;
2,In addition，‘Run make bootstrap’ What means，what should I do？

**Comment by justinswart** [comment]
Hi, it sounds like you need to run `make bootstrap` from the terminal. This is a shell command which will build the dependencies for the project.

Also make sure that your command line tools are also set to use Xcode 11.5.
