### ISSUE TITLE
no team account

### ISSUE THREAD

**Issue by LeoWang0219** [kickstarter/ios-oss#1238]
No account for team "48YBP49Y5N". Add a new account in the Accounts preference pane or verify that your accounts have valid credentials.
No profiles for 'com.kickstarter.kickstarter.debug' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.kickstarter.kickstarter.debug'.

**Comment by justinswart** [comment]
Hi, it sounds like you're trying to build the app onto your device. I would suggest using a simulator or configuring it to use your own Apple developer account details. I'm afraid we can't assist you with how that all works but there is documentation on the Apple developer site:

https://developer.apple.com/
