### ISSUE TITLE
'liveView' is deprecated in Playground Pages

### ISSUE THREAD

**Issue by timcamber** [kickstarter/ios-oss#124]
I get the following error when trying to build and run the playgrounds in the project in Xcode 8.2:

`warning: 'liveView' is deprecated: Use 'PlaygroundPage.current.liveView' from the 'PlaygroundSupport' module instead`

Is this expected?

**Comment by mbrandonw** [comment]
we just upgraded everything to xcode 8.3 and swift 3.1, which has a lot of fixes for playgrounds. so please try `master` on the newest xcode
