### ISSUE TITLE
Code that doesn't understand

### ISSUE THREAD

**Issue by SGExploring** [kickstarter/ios-oss#1247]
I am a novice swift developer, can you tell me how to understand the "\" in "|> \.backgroundColor .~ UIColor.white"

**Comment by justinswart** [comment]
Hi there, `|>` is the _pipe forward_ operator and `.~` is the `set` operator. The definition for `|>` is [here](https://github.com/kickstarter/Kickstarter-Prelude/blob/master/Prelude/Function.swift#L9) and `.~` [here](https://github.com/kickstarter/Kickstarter-Prelude/blob/master/Prelude/Lens.swift#L62).

`|>` forwards a value to a function, so using the example:

```swift
button |> \.backgroundColor .~ .white
```

We are forwarding the value `button` to the function returned from `\.backgroundColor .~ .white`.

The syntax is a little hard to read at first if you're unfamiliar with these concepts, this in particular refers to something called Lenses. If you're interested I would suggest these resources:

Talk on Lenses: https://www.youtube.com/watch?v=ofjehH9f-CU
PointFree: https://www.pointfree.co/
