### ISSUE TITLE
No such Module 'Argo'

### ISSUE THREAD

**Issue by AutomationAnkur** [kickstarter/ios-oss#1307]
I am getting No such Module 'Argo' error while compiling

_Below two errors I can see on terminal with make bootstrap_
**Error**: Calling Non-checksummed download of carthage formula file from an arbitrary URL is disabled! Use 'brew extract' or 'brew create' and 'brew tap-new' to create a formula file in a tap on GitHub instead.
If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/Homebrew/homebrew-core/issues/new
**Error**: carthage does not have a version "0.34.0" in the Cellar.

Can someone please help!!

**Comment by justinswart** [comment]
Hi, the project was recently updated for Xcode 12. Ensure that you have Xcode 12 command line tools set as the default, delete the local `Carthage` dir and try to run `make bootstrap` again.
