### ISSUE TITLE
Not able to build project

### ISSUE THREAD

**Issue by tejuamirthi** [kickstarter/ios-oss#1314]
Go ahead if this project is open for contribution, else let me know and close the issue.

Can you give more description about Xcode version, how to build the project because I'm not able to.
The KsApi.Secrets.isOSS = true, where can we set this in the project. 
Can anyone explain this or update the readme?

I'm just exploring, checking different projects and came across this one. Hope you don't mind

Thanks in advance

**Comment by justinswart** [comment]
Hi @tejuamirthi, you should be able to build using Xcode 12 (make sure your command line tools are also set to Xcode 12). Then run `make bootstrap` in terminal. Also try deleting the `Carthage` directory and running `make bootstrap` again.

**Comment by tejuamirthi** [comment]
Still not able to run @justinswart

**Comment by ankushkushwaha** [comment]
> Hi @tejuamirthi, you should be able to build using Xcode 12 (make sure your command line tools are also set to Xcode 12). Then run `make bootstrap` in terminal. Also try deleting the `Carthage` directory and running `make bootstrap` again.

I was missing `make bootstrap` . Thanks it resolved my issue.
