### ISSUE TITLE
Hi, how i can use pipe forward in our project

### ISSUE THREAD

**Issue by hprobotic** [kickstarter/ios-oss#133]
When i try to add this function:
```
/**
 Pipe a value into a function.
 
 - parameter x: A value.
 - parameter f: A function
 
 - returns: The value from apply `f` to `x`.
 */
public func |> <A, B> (x: A, f: (A) -> B) -> B {
    return f(x)
}
```
 to our project. Xcode notices an error:
`Operator implementation without matching operator declaration` on | character

**Comment by justinswart** [comment]
Hi @hprobotic, have a look at our [Prelude](https://github.com/kickstarter/Kickstarter-Prelude) library. You would first need to declare the `infix operator` before implementing it. This is done in https://github.com/kickstarter/Kickstarter-Prelude/blob/master/Prelude/Operators.swift.

**Comment by hprobotic** [comment]
I got it, thanks
