### ISSUE TITLE
Bootstrap fails because of Alamofire

### ISSUE THREAD

**Issue by andreacipriani** [kickstarter/ios-oss#1357]
Hey, just reporting that the bootstrap seems to fail.

How to reproduce:

- Clone the repo `git clone git@github.com:kickstarter/ios-oss.git`
- Run `make bootstrap`

Expected: command succeds
Observed: `Building scheme "Alamofire iOS" in Alamofire.xcworkspace Build Failed`

**Comment by singhhari** [comment]
Hi @andreacipriani. After XCode 12 was released, there appears to be an issue with Carthage that requires a manual workaround as referenced [here](https://github.com/Carthage/Carthage/blob/master/Documentation/Xcode12Workaround.md). 

Within the repo we have a script that includes this workaround and you can call it on the command line with `bin/carthage.sh`.

**Comment by justinswart** [comment]
hi @andreacipriani please pull the latest changes and ensure you're using Xcode 12.2 or 12.3 and that your command line tools also use the same version.

Sometimes you may need to trash your `Carthage` directory and run `bin/carthage.sh` again.
