### ISSUE TITLE
Use flatMap instead compact

### ISSUE THREAD

**Issue by hprobotic** [kickstarter/ios-oss#136]
```
public extension Array where Element: OptionalType {

  /**
   - returns: A new array with `nil` values removed.
   */
  public func compact() -> [Element.Wrapped] {
    return self.filter { $0.optional != nil }.map { $0.optional! }
  }
}
```
We are making this new protocol OptionalType & extend Optional to confront to this only to write the compact function above? 
with compact we can use flatMap like array.flatMap({ $0 })

**Comment by justinswart** [comment]
Hi @hprobotic, `compact()` does not perform any transformation on the values in the array. It's true that `flatMap` in many instances would have the same result but this is more of a lucky coincidence in that Swift provides an overload for `flatMap` that does this (it flattens Optional wrappers):

```
public func flatMap<ElementOfResult>(_ transform: (Element) throws -> ElementOfResult?) rethrows -> [ElementOfResult]
```
As this documentation says:
```
/// Use this method to receive an array of nonoptional values when your
/// transformation produces an optional value.
```

Remember that `flatMap` 'flattens' and then 'maps' (transforms) so we could introduce undesirable results if we were to call this on an array containing arrays that we didn't wish to transform in any way:

`[[1], [2, 3], []]` would become `[1, 2, 3]` despite us only wanting to eliminate nils from it.

@mbrandonw can elaborate on the above or correct me if I'm wrong ☺️

**Comment by hprobotic** [comment]
Ya, just take a look on ios-oss project and didn't find anywhere use compact as your idea.
Btw, that is pretty good thing when you write it in Prelude as a Library 
Thanks you again for explain that

**Comment by mbrandonw** [comment]
@hprobotic we find the overloaded usage of `flatMap` a bit confusing. in one instance it is the standard `(A -> [B]) -> [A] -> [B]` that you would see in other [languages](https://www.haskell.org/hoogle/?hoogle=concatMap), and in the other it's `(A -> B?) -> [A] -> [B]` which is typically given another name in other [languages](https://www.haskell.org/hoogle/?hoogle=mapmaybe).

this confusion is amplified in a language like swift that will "magically" promote non-optionals to optionals where it sees fit, so we prefer to skip with more semantic definitions of `flatMap` and provide a new concept for removing `nil`s from an array.

**Comment by hprobotic** [comment]
Thanks you all 💯
