### ISSUE TITLE
running "make bootstrap" it is failing with carthage: command not found

### ISSUE THREAD

**Issue by bemini** [kickstarter/ios-oss#1378]
As shown in "Getting Started" steps
1. Install XCode
2. Cloned the repository
3. run make bootstrap to install tools and dependencies

Result:
It fails with error "carthage: command not found"

![image](https://user-images.githubusercontent.com/10479571/109073538-84495c80-76c4-11eb-8fb1-d204aabe4c98.png)

**Comment by singhhari** [comment]
Hey @bemini you have a few different options for installing `Carthage`. Please refer to their official documentation here:
https://github.com/Carthage/Carthage#installing-carthage
