### ISSUE TITLE
Any plan to upgrade to Swift 3?

### ISSUE THREAD

**Issue by lexrus** [kickstarter/ios-oss#14]
Swift 2.3 would be deprecated in the next release of Xcode. Do you have any plan to upgrade the entire code base and dependencies?

**Comment by mbrandonw** [comment]
Yeah for sure! It'll probably be the first thing we do in the new year. Stay tuned for the massive PR...

**Comment by evgeniyd** [comment]
@mbrandonw so, will you be doing the migration in-house and without involving open-source community?

**Comment by stephencelis** [comment]
@evgeniyd We'll be doing the migration in the open on branches and definitely won't turn down community help! 😄

**Comment by damianesteban** [comment]
I would love to give a hand.  This project is such an amazing resource.

**Comment by jorgecasariego** [comment]
Great to hear that @evgeniyd 

Like @damianesteban I'd love to help in this project!

**Comment by mfclarke** [comment]
Volunteering over here 👋

**Comment by mbrandonw** [comment]
Hi everyone! We've begun the Swift 3 migration, and it's doozy! We don't see a clear way of sharing this work, but if yer interested in following along or critiquing our methods, here are some PR's we've done so far:

https://github.com/kickstarter/Kickstarter-Prelude/pull/62
https://github.com/kickstarter/Kickstarter-ReactiveExtensions/pull/54
https://github.com/kickstarter/ios-ksapi/pull/3

**Comment by heshamsalman** [comment]
Hey @mbrandonw I've migrated several ~900 class Swift projects to Swift 3 in the last month or so, (also the author of https://buildingvts.com/a-mostly-comprehensive-list-of-swift-3-0-and-2-3-changes-193b904bb5b1) 

I'd like to share lessons learned doing these large migrations:
- If you use `@IBAction`, don't refactor your action code to look like: `@IBAction func doTheThing(button: UIButton) { ... }`. Leave the anonymous first parameter in the method definition.
- *Push Notifications*. If you were doing something like this to convert your device token to a string (I've seen this everywhere) your pushes are going to break: 

```swift
return String(data: deviceToken.base64EncodedData(), encoding: .utf8)?
             .trimmingCharacters(in: CharacterSet.whitespaces)		
             .trimmingCharacters(in: CharacterSet(charactersIn: "<>"))		
             ?? ""
```

Realistically, the right way is to treat PN deviceTokens as `Data`, but in lieu of that, here's some _magic code_ to do it: `return deviceToken.reduce("", {$0 + String(format: "%02X", $1)})`

- *Networking* (but really, value types). `AnyObject` used to be the gold standard for networking, and for any _thing_. That's been replaced by `Any`, which is no longer a representation of a _type_ but a representation of a _value_. Basically, things that are `class` objects are `AnyObject`, but `struct` are `Any`. This has far reaching implications. In general, you don't want to use `AnyObject` unless you're communicating with an Obj-C class. 

If you run into any issues or would like me to take a section, just LMK. 👍

**Comment by mbrandonw** [comment]
@heshamsalman wow, thanks for all of the info! definitely the `Any`/`AnyObject` difference has definitely been the biggest gotcha we've experienced!

we just opened a PR that converts our `Library.framework` to Swift 3 https://github.com/kickstarter/ios-oss/pull/26, which is more than half of the app code. Still a long ways to go, but we're making progress!

**Comment by mbrandonw** [comment]
oh, and btw @heshamsalman, this is how we do our push token transformation: https://github.com/kickstarter/ios-oss/blob/master/Kickstarter-iOS/ViewModels/AppDelegateViewModel.swift#L629-L634. That's swift 2 code, hasn't been updated to swift 3 yet. i'll keep your comments in mind when i get to that code! thanks again!

**Comment by mbrandonw** [comment]
Hey everyone, we just completed our Swift 3 migration https://github.com/kickstarter/ios-oss/pull/26 so I'll close this one now. Thanks for the interest!
