### ISSUE TITLE
xcframework

### ISSUE THREAD

**Issue by funzin** [kickstarter/ios-oss#1459]
Do you have plan using xcframwork created by carthage?

Can replace the following library to xcframework.
```
Alamofire.xcframework
AlamofireImage.xcframework
FBSnapshotTestCase.xcframework
Optimizely.xcframework
Prelude.xcframework
Prelude_UIKit.xcframework
ReactiveExtensions.xcframework
ReactiveExtensions_TestHelpers.xcframework
ReactiveSwift.xcframework
```
If you want xcframework, I will create PR.

**Comment by justinswart** [comment]
Hi @funzin I'm interested to know more, is this in order for us to use SPM?

**Comment by funzin** [comment]
- Carthage supported xcframework from 0.37.0 (ref: https://github.com/Carthage/Carthage/releases/tag/0.37.0)
- Changing from Carthage to SPM is not easy
  - Library which doesn't support SPM exists 
- Some frameworks can be changed to xcframework by using carthage
