### ISSUE TITLE
Questiona about ViewModels architecture

### ISSUE THREAD

**Issue by Czajnikowski** [kickstarter/ios-oss#15]
First things first... I LOVE you guys for sharing your project with the World. I believe you're making a huge contribution to the community ❤️ 

Today I started exploring your codebase. I absolutely love your Playground Driven Development™️ approach and will get to it soon, but I've started with AppDelegate and View Models first.

I seen your [doc about the structure of VMs](https://github.com/kickstarter/native-docs/blob/master/vm-structure.md) and I like the idea of composing them out of `inputs` and `outputs`. The concern I always had in my code was "How to clearly separate inputs and outputs in VMs?" and you solved it in your design, but at the same time by conforming to `...ViewModelInput` and `...ViewModelOutput` in `...ViewModel` you've broken the clear separation, so now placing a . after View Model object in code gives overwhelming breadth of opportunities 😉 

I believe that having `inputs` and `outputs` as a separate objects (such a shame that we cannot make anonymous classes in Swift) and removing conformance out of View Model itself will highly improve understandability and ease of use of your code. What do you think, maybe I overlooked something, or your design decision have some other background?

All the best and thanks again!

**Comment by Czajnikowski** [comment]
Ok, I see it now - obviously you're using `AppDelegateViewModelType` in AppDelegate 😅 

I'll carry on!

**Comment by stephencelis** [comment]
@Czajnikowski Thanks for your comments! Yup, by using the protocol type we're forced to reach through `inputs` and `outputs` each time, though it's definitely a matter of discipline 😄

If you wanna see an alternate approach we've toyed around with, check out our reusable pagination "view model"](https://github.com/kickstarter/ios-oss/blob/66087aac35e295c1c3064c25e916680a621fbbb6/Library/Paginate.swift). it's not even a class, just a function of signal inputs to outputs!
