### ISSUE TITLE
ReactiveExtensions-TestHelpers-iOS   build  fail

### ISSUE THREAD

**Issue by BinBear** [kickstarter/ios-oss#1524]
*** Checking out stripe-ios at "v18.0.0"
*** Checking out appcenter-sdk-apple at "4.0.0"
*** Checking out Kickstarter-ReactiveExtensions at "2fceab5217b819986c7adf7334e27ad6e008b4b6"
*** Checking out appboy-segment-ios at "4.0.0"
*** Checking out AlamofireImage at "4.1.0"
*** Checking out Kickstarter-Prelude at "9118beee2b37fa5fc5a4f56502c1fa99030b9f9e"
*** Checking out analytics-ios at "4.1.2"
*** Checking out swift-sdk at "v3.6.1"
*** Checking out ios-snapshot-test-case at "6.2.0"
*** Checking out ReactiveSwift at "6.5.0"
*** Checking out facebook-objc-sdk at "v6.5.2"
*** Checking out Alamofire at "5.4.3"
*** xcodebuild output can be found in /var/folders/xv/g9cjb0ms02x9x4ln22z4j80m0000gn/T/carthage-xcodebuild.tNhNRr.log
*** Downloading binary-only framework appboy_ios_sdk_full at "https://raw.githubusercontent.com/Appboy/appboy-ios-sdk/master/appboy_ios_sdk_full.json"
*** Downloading analytics-ios binary at "4.1.2"
*** Downloading appboy-segment-ios binary at "4.0.0"
*** Downloading binary-only framework FirebaseAnalyticsBinary at "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json"
*** Downloading appcenter-sdk-apple binary at "4.0.0"
*** Downloading facebook-objc-sdk binary at "Facebook SDK v6.5.2"
*** Downloading binary-only framework FirebaseCrashlyticsBinary at "https://dl.google.com/dl/firebase/ios/carthage/FirebaseCrashlyticsBinary.json"
*** Downloading binary-only framework FirebaseInAppMessagingBinary at "https://dl.google.com/dl/firebase/ios/carthage/FirebaseInAppMessagingBinary.json"
*** Downloading binary-only framework FirebasePerformanceBinary at "https://dl.google.com/dl/firebase/ios/carthage/FirebasePerformanceBinary.json"
*** Downloading binary-only framework FirebaseProtobufBinary at "https://dl.google.com/dl/firebase/ios/carthage/FirebaseProtobufBinary.json"
*** Downloading ios-snapshot-test-case binary at "6.2.0"
*** Downloading binary-only framework PerimeterX at "https://raw.githubusercontent.com/PerimeterX/px-iOS-Framework/master/PerimeterX.json"
*** Downloading stripe-ios binary at "Version 18.0.0"
***  Skipped installing ios-snapshot-test-case binary due to the error:
	"Incompatible Swift version - framework was built with 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7) and the local version is 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)."

    Falling back to building from the source
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "AlamofireImage iOS" in AlamofireImage.xcworkspace
*** Building scheme "FBSnapshotTestCase iOS" in FBSnapshotTestCase.xcworkspace
*** Building scheme "Prelude-iOS" in Prelude.xcodeproj
*** Building scheme "Prelude-UIKit-iOS" in Prelude.xcodeproj
*** Building scheme "ReactiveExtensions-iOS" in ReactiveExtensions.xcodeproj
*** Building scheme "ReactiveExtensions-TestHelpers-iOS" in ReactiveExtensions.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/vin/Desktop/GitHub/ios-oss/Carthage/Checkouts/Kickstarter-ReactiveExtensions/ReactiveExtensions.xcodeproj -scheme ReactiveExtensions-TestHelpers-iOS -configuration Release -derivedDataPath /Users/vin/Library/Caches/org.carthage.CarthageKit/DerivedData/12.5_12E262/Kickstarter-ReactiveExtensions/2fceab5217b819986c7adf7334e27ad6e008b4b6 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/xv/g9cjb0ms02x9x4ln22z4j80m0000gn/T/Kickstarter-ReactiveExtensions SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/vin/Desktop/GitHub/ios-oss/Carthage/Checkouts/Kickstarter-ReactiveExtensions)

**Comment by singhhari** [comment]
Hi @BinBear it seems like you are running into issues with our Carthage dependencies. Can you provide some details on the version of Xcode you are running on?

**Comment by justinswart** [comment]
Our main branch has not yet been update for Xcode 12.5, we're working on that [here](https://github.com/kickstarter/ios-oss/pull/1497) but still have some issues we're trying to fix.

**Comment by BinBear** [comment]
@singhhari  Xcode version  12.5

**Comment by BinBear** [comment]
@justinswart  Can I just wait for you to fix it now?
