### ISSUE TITLE
Any further plan with Realm

### ISSUE THREAD

**Issue by hprobotic** [kickstarter/ios-oss#160]
Hi @folks 
I am working on side-project base on your source structure for a couple of months. I learned a lot of new things. And I have some questions:
- Why we don't try to use cache database: Core Data, Realm.
- Why we don't define data model as class instead struct

Thanks

**Comment by stephencelis** [comment]
Glad our project has helped!

> Why we don't try to use cache database: Core Data, Realm.

Most of our app requires an internet connection, so we've optimized our development around that for now. We may revisit offline use cases later, though!

In general, were we to use caching or a database, our input signals would merge our API response data with our caching/database layer, and we'd add an output for things we want to cache/save.

> Why we don't define data model as class instead struct

We prefer to treat data as data (and immutable data at that) for ease of testing, predictability/readability, and thread-safety, so the value semantics of structs makes sense for us. The reference semantics that classes provide generally run against these goals.

Classes are, on the other hand, slightly more performant in Swift at this time. Were we to hit a significant performance bottleneck, we could swap out any problematic structs with a `final`, immutable, class, but we generally want to avoid this.
