### ISSUE TITLE
[Idea] Remove `Screenshots` from repo 

### ISSUE THREAD

**Issue by tuduongquyet** [kickstarter/ios-oss#1600]
I think we should remove `Screenshots` folder from our repo, rewriting history also since it's NOT `friendly` for CI/CD.

**Comment by singhhari** [comment]
Hey @tuduongquyet thanks for the suggestion. We actually cache these screenshots in between runs because the test suite takes quite a while to take all the screenshots. For that reason, we leave the screenshots folder in, so we can minimize the potential CI/CD time between each run.
