### ISSUE TITLE
Explain your playground workflow?

### ISSUE THREAD

**Issue by AndrewSB** [kickstarter/ios-oss#161]
First of all: thank you for deciding to go open source. Tons of learnings in this repo 🙏

I was wondering how y'all generated and engineered with your playgrounds. Are they auto-generated or handwritten per-controller?
Also, how are they used by Kickstarter engineers? Are they used 

1. whilst creating new views (i.e. one would create a view with a vm, setup inputs and outputs, and then create a playground to have a hot-reloady environment to build the view), or 
2. as artifacts to admire once a view is completely built, and as a tool to confidently make changes to existing views + for sanity checking and screenshot testing to prevent UI regressions?
Or both?

Also: I do love how you've modeled the `AppEnvironment` and used it's co-effecting qualities to such great effect ❤️

**Comment by mbrandonw** [comment]
It is definitely both! In particular:

1) Yes absolutely, we find that playgrounds can be a nice replacement for a lot of the things that storyboards and the simulator provide. 

2) Definitely, playgrounds are the simplest way to spin up a controller in any state we want without needing to actually run the app, potentially log in as a user with some configuration, navigate through to a screen, etc etc etc...

**Comment by AndrewSB** [comment]
Awesome to hear 😄 

I'm going to try it out with the next app I'm working on 😄 
Do you guys have a way to auto generate a playground through a script, or is it all manual right now?

**Comment by mbrandonw** [comment]
just manual!
