### ISSUE TITLE
naming nitpick: "ViewModel"

### ISSUE THREAD

**Issue by AndrewSB** [kickstarter/ios-oss#164]
I see that you use the name `ViewModel` for objects that have no inherent view (e.g. the `AppDelegateViewModel`) and I'm confused as to why. Can you explain why you chose to name objects with that role as `ViewModel`s?

To me, your `ViewModel`s seem like MVC controllers since they do many MVC control-y things; they don't simply map models into a viewable format. That comes with it's own host of issues of bloated controllers: anything that isn't view or data related becomes controller territory - persistence, networking, etc.
The iOS community has become very trigger happy calling objects that reduce code in a view controller a "view model"  ever since MVVM became popular

From my understanding, it seems like you folks are using your view controllers simply as views that ferry messages back and forth from a view model, and your view models are making all of the hard decisions. 
That to me no longer sounds like an object that maps data -> view (a view model), and more like a controller (terribly broad name, I agree)

The reason I'm asking is not to beat a dead horse or go into a naming holy war (please stop me if that's the direction this is heading in), but because I'm genuinely curious as to why you decided to classify your objects in the way you did 😛

**Comment by mbrandonw** [comment]
lol boy oh boy have we talked about this quite a bit! we honestly don't really care about the name at all. we see our objects as just sugar around transforming user input signals to user observable output signals. it makes things easy to test (we have over 1,000 tests with over 7,000 assertions). we've even gone as far to model these things as just a pure function from input signals to output signals, like our [paginate function](https://github.com/kickstarter/ios-oss/blob/master/Library/Paginate.swift), which handles pagination for the entire app.

so yeah, we really don't wanna think about the naming of this thing at all. just wanna think of it as the "functional core" as mentioned in gary berhardt's talk https://www.destroyallsoftware.com/talks/boundaries

**Comment by AndrewSB** [comment]
😂😂 totally on the same wavelength, I watched a bunch of the 2017 functional swift talks on Tuesday (thank you for hosting), and was planning on re-watching boundaries later today since it's been about a year since I last thought about berhardt's 

Paginate is really well done, it reminds me of the something [similar I wrote](https://gist.github.com/AndrewSB/9585bcb32fb669d64b73b7a9237eed3b), but way more thought out!

I agree with thinking of your view models as the highly-tested functional core of your app, and you're going to get along _fine_ (as you have been) with a less-specific-that-it-could-be name, but names are important.
They give identity and help engineers understand if code belongs in `ObjectName`. Even renaming your objects to be `Core`s might leave the codebase in a more understandable state, where one no longer has to have the cognitive overhead of substituting `view model` -> `functional core` (small, albeit). `AppDelegateCore`, or a `AppDelegateController`, give it some thought 😊
Also, https://blog.codinghorror.com/i-shall-call-it-somethingmanager/ is a classic. I would recommend a read, if you haven't already.

Also, I really enjoyed @DivineDominion's clean [example of a ReSwift app](https://github.com/DivineDominion/ReSwift-CustomRouting). Specifically creating an [`App`](https://github.com/DivineDominion/ReSwift-CustomRouting/blob/master/ReSwift-CustomRouting/Application/App.swift) to keep his [`AppDelegate`](https://github.com/DivineDominion/ReSwift-CustomRouting/blob/master/ReSwift-CustomRouting/Infrastructure/AppDelegate.swift) slim.
 
And of course, take my armchair criticism with a grain of salt, I'm sure you guys have important things to work on and features to ship that take precedence over renaming objects, or moving code.

PS
1. Really awesome that you have your system that well tested, it must feel really good to be able to confidently make changes as you do.
2. what you said about finding a bug, and then writing a failing test to pinpoint the bug sounds incredible - it's always been something I've wanted to do, but I haven't gone through with it. Next time 👌

**Comment by stephencelis** [comment]
Something we've wanted to explore for awhile (but haven't had the time to at length) is to try the `paginate` model everywhere. Then we can just have a `static func main` on the view controller, app delegate, wherever, or have descriptive top-level functions.

**Comment by AndrewSB** [comment]
@stephencelis: I vote for keeping them in a namespace, be that static functions on existing objects, or something like 

```swift
class Global {
    static func paginate(...) {}

    static func otherPureGlobal(...) {}
}

```

**Comment by stephencelis** [comment]
Great thing about Swift modules is we get namespaces for free! `Kickstarter_iOS`, `Library`, etc. 😄

If we wanted additional namespacing, I'm thinking we'd probably use our controllers.

**Comment by AndrewSB** [comment]
oh right! totally forgot about that, I actually use that all the time too! I usually define an `Error` in my app module, and then refer to it as `MyApp.Error`, and the swift error protocol through `Swift.Error`.

I take back what I said then, carry on 😄
