### ISSUE TITLE
Check dependencies Error

### ISSUE THREAD

**Issue by JolieYang** [kickstarter/ios-oss#17]
when I run on Simulator, It's ok.But run on iPhone,It's show the "check dependencis"error.
Detail: 
"Check dependencies
CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 9.3'"'

How to fix this?Thanks

**Comment by digoreis** [comment]
@JolieYang  you try this: http://stackoverflow.com/questions/29836356/ios8-dynamic-frameworks-codesign-error-code-signing-is-required-for-product

In this case, you try signing to framework.

**Comment by mbrandonw** [comment]
we just merged swift 3 support https://github.com/kickstarter/ios-oss/pull/26 and so now xcode 8.2 can be used. This may fix the problem.

closing this for now, let us know if you have any questions.
