### ISSUE TITLE
Open specific project page on Kickstarter app from another app using with CFBundleURLSchemes 

### ISSUE THREAD

**Issue by cahitatlas** [kickstarter/ios-oss#1760]
Hi. How can i forward my app's user to spesific Kickstarter project page with CFBundleURLSchemes?

**Comment by msadoon** [comment]
Hi @cahitatlas, 

To answer your question: Any kickstarter project (even prelaunch projects), can be deeplinked into the app via their web url by replacing `https://` with `ksr://`. That's a recognized `CFBundleURLScheme` in our app. 

**Example**
web url: 
`https://www.kickstarter.com/projects/rest/sitpack-campster-2?ref=section-homepage-view-more-recommendations-p1` 

should deeplink from another app as 

`ksr://www.kickstarter.com/projects/rest/sitpack-campster-2?ref=section-homepage-view-more-recommendations-p1`

For more info on all supported deeplink routes check `Navigation` `deepLinkRoutes` and corresponding `AppDelegateViewModel` `deepLinkMatch`.
