### ISSUE TITLE
about import class

### ISSUE THREAD

**Issue by Chakery** [kickstarter/ios-oss#18]
Hello, I am a green hand in Swift, this is the very first time that I know `import class UIKit.UIView`.
I would like to ask you for help that what is specific meaning of the following code in three lines ? 
Thank you so much and look forward your reply!

```
import class UIKit.UIView

import UIKit.UIView

import UIKit
```

**Comment by Czajnikowski** [comment]
Hi! I didn't know about it as well 😉  Check the "Import Declaration" section in "The Swift Programming Language". In my english version for Swift v3.0.1 it's on p. 634.

Cheers

**Comment by mbrandonw** [comment]
Yeah, it's an underutilized feature of Swift. We tried it out at the beginning but ultimately decided not to stay with it.
