### ISSUE TITLE
Question about `paginate` function in ViewModel

### ISSUE THREAD

**Issue by KimSmitth** [kickstarter/ios-oss#184]
Hello there. I am trying to understand the how the `paginate` function works in ViewModel for recent several days.

````swift
    let (paginatedActivities, isLoading, pageCount) = paginate(
            requestFirstPageWith: requestFirstPage,
            requestNextPageWhen: isCloseToBottom,
            clearOnNewRequest: false,
            valuesFromEnvelope: { $0.activities },
            cursorFromEnvelope: { $0.isEnd == "1" ? pageCount : ++pageCount },
            requestFromParams: { _ in AppEnvironment.current.apiService.getGameJoinPlayers(gameId: "", page: pageCount) },
            requestFromCursor: { AppEnvironment.current.apiService.getGameJoinPlayers(gameId: "", page: pageCount)})
````

The code from kickstarter is using  `moreActivities` url for the next pagination signalProducer.

For some reason, the existing codebase now we using is passing a parameter called `page` to request the pagination data and an `isEnd` which return from my backend server *(we call it cursor?)* to indicate the pagination whether is end or not. So the `cursorFromEnvelope` closure I am trying to do something like `$0.isEnd == "1" ? nil : ++pageCount`.

So there is a question: How to use the `pageCount` recursively which return from the paginate function? And so that we can somehow unify the  `requestFromParams` and `requestFromCursor` to use the same closure for signalProducer , cause the `requestFromParams` and `requestFromCursor` functions are actually using the same request but with a different page count parameter ?

Thanks for you patient answering this.

**Comment by justinswart** [comment]
Hi @KimSmitth I'm not sure of your exact use-case but it sounds like you are using page-based pagination. Our `pagination` function is specific to cursor-based pagination and could have unexpected behaviour when used in another way.

However if you inspect the `paginate` function you will see that `valuesFromEnvelope` and `cursorFromEnvelope` are both generic over `Envelope`, one returns a generic array of `Value` and the other a generic `Cursor`. It would be possible then to return the `Cursor` that you require, this could be a tuple containing the various parameters that you need.

In our usage we differentiate between the initial request and the paginated request and therefore have used separate closures and `SignalProducer`s for these respectively.

**Comment by KimSmitth** [comment]
Thanks for answering this!
