### ISSUE TITLE
KickStarter is coming to Japan

### ISSUE THREAD

**Issue by PeterTeng** [kickstarter/ios-oss#187]
Kickstater is coming to Japan, is there any help needed with translation?

https://www.kickstarter.com/japan

**Comment by hirokihori** [comment]
I'm willing to help some translation too. Let us know.

**Comment by stephencelis** [comment]
Thanks so much for the interest! 😄

Translation is already built into our general flow, but feel free to pass along any feedback with the translations once they're available! We'll be happy to forward comments on to our team.
