### ISSUE TITLE
How are you guys generating your screenshots?

### ISSUE THREAD

**Issue by cloudface** [kickstarter/ios-oss#213]
Hello

I saw that you guys have a lot of screenshots on various devices in various orientations and in multiple languages. I also saw that you guys are not using fast lane's snapshot to do this. How are you guys generating these screenshots? I'm looking for a way to do that and with fast lane's snapshot I'm forced to use the UI Automation framework which makes it a bit tricky to mock underlying dependencies of my app to produce the desired states which I want to screenshot. Thanks for your input!

Kind regards
Chris

**Comment by stephencelis** [comment]
We use [FBSnapshotTestCase](https://github.com/facebook/ios-snapshot-test-case) to generate our screen shots, which will actually fail the test suite if a screenshot doesn't match the historical version!

An example use:

https://github.com/kickstarter/ios-oss/blob/master/Kickstarter-iOS/Views/Controllers/DashboardViewControllerTests.swift#L41-L52

We use a single app environment to manage global mutable state (like locale, language, current time, api client, etc.), which allows us to push and pop changes quickly and easily. More info on that can be seen in this talk: https://academy.realm.io/posts/try-swift-brandon-williams-writing-testable-code/

**Comment by cloudface** [comment]
Thank you for the quick reply! We use carthage in our project to manage our dependencies and FBSnapshotTestCase doesn't support it (only Cocoapods). How are you guys dealing with your dependencies? I see you have a makefile but I couldn't make out what kind of build system you guys are using.

**Comment by stephencelis** [comment]
We use git submodules and drag the associated project files into our main project (see [Makefile#L45-L47](https://github.com/kickstarter/ios-oss/blob/743f9992596e452c8cbaadfbede220df044a3ce9/Makefile#L45-L47)). We have very few dependencies (and half of them internal), so manually managing submodules hasn't been an issue!

**Comment by cloudface** [comment]
Gitsubmodules is an interesting way to do it, thanks for the tip! I will look into that. Thanks again for the help!
