### ISSUE TITLE
Dispatch Model updates

### ISSUE THREAD

**Issue by alexbredy** [kickstarter/ios-oss#23]
Hi there! Thanks for sharing the project with the open source community, it's a great learning resource!

I was wondering how are you dispatching an update done to a model to all the View Controllers that are displaying it? 

eg: updating a Project's name and see the new name on all the View Controllers that are showing this project (without having to reload the data from the server)

Thanks!

**Comment by AndrewSB** [comment]
this would be really interesting to hear 😄

**Comment by justinswart** [comment]
Hey, I think you're asking is whether we make use of some sort of reactive bindings to reflect model changes in the view? We don't currently do this, instead we refresh models via our REST api when we need to.

Example:

https://github.com/kickstarter/ios-oss/blob/master/Library/ViewModels/ProjectPamphletViewModel.swift#L58

The signal `freshProjectAndLiveStreamsAndRefTag ` emits when the viewModel is configured AND `viewDidAppear` is called OR `viewDidLoad` is called.

Each time we `switchMap` onto the `fetchProjectAndLiveStreams(_:_:)` function which returns `SignalProducer<(Project, [LiveStreamEvent]?), NoError>` with the refreshed data that we require.

**Comment by alexbredy** [comment]
Thanks for your reply and explanation @justinswart . Looking forward to see how this part will evolve.
