### ISSUE TITLE
No such module 'Alamofire' in AlamofireImage iOS Target

### ISSUE THREAD

**Issue by AmarJayR** [kickstarter/ios-oss#24]
I'm unable to build any of the other targets because they all end up with this error. The first occurence of this error is on line 23 of AlamofireImage.xcodeproj>Source>ImageDownloader.swift

The Alamofire target builds without error.

I am building in Xcode 7.3.1 (Swift 2.2) for the iPhone 6s Plus simulator (though this error occurs for all simulators) and make test-all passes with no errors.

Thank you for open-sourcing this project, and I'm very excited to take a look at it!

**Comment by stephencelis** [comment]
Could you please provide more details, especially the error message and the steps you've gone through to from initial `git clone` to build? A screenshot would also help!

**Comment by AmarJayR** [comment]
Hi @stephencelis, thank you for your prompt response. I just recloned the project and here are the steps I took:

1. Began with `git clone https://github.com/kickstarter/ios-oss.git`
2. Ran `make bootstrap` (no errors besides the native-secrests error which is ignored)
3. Ran `make test-all` which successfully launches the KickDebug app. Upon completion I receive `** TEST SUCCEEDED **`
4. Open Kickstarter.xcodeproj in Xcode 7.3.1
5. Like recommended in #9 I first build `Kickstarter-Framework-iOS` which fails because of AlamofireImage

![screen shot 2016-12-20 at 9 34 28 am](https://cloud.githubusercontent.com/assets/2224447/21361147/9b712f0a-c697-11e6-9e5f-9c7647e94d95.png)
![screen shot 2016-12-20 at 9 34 19 am](https://cloud.githubusercontent.com/assets/2224447/21361146/9b705634-c697-11e6-880d-60bd512f4692.png)

**Comment by stephencelis** [comment]
I wonder if this is related to some stale build artifacts or simulator data.

- If you try to build the Alamofire framework target directly does it fail with a different error?
- Have you tried **Clean Build Folder…**? (Hold option while opening the **Product** menu.)
- Have you tried to reset your simulators?

**Comment by AmarJayR** [comment]
Everything builds perfect now! Your **Clean Build Folder** suggestion made me realize that I had my Derived Data location set to `Legacy` instead of `Unique`. 

Thank you for your rapid responses!

**Comment by MaveyMa** [comment]
Can you please document the steps you took the solve this error?

**Comment by thenameisdavid** [comment]
> Can you please document the steps you took to resolve this error?

Since nobody else bothered to respond: The two cleaning methods I regularly use: CMD + shift + K , and CMD + alt + shift + k .
