### ISSUE TITLE
(Question) Using default HTML Parser

### ISSUE THREAD

**Issue by arjunpa** [kickstarter/ios-oss#25]
Hey. I see you're using NSHtmlTextDocumentType while initing NSAttributedString to parse and present html. I went through your code and I'm not sure you're caching the result. You're also required to use this from the main queue. The reason why I bought this up is I have been using it in my own project and I have seen some really weird crashes whenever I use it in a TableView or CollectionView and reload a cell or the whole view. Have you experienced anything similar? I have been using DTCoreText as an alternative.

**Comment by mbrandonw** [comment]
@arjunpa oh interesting, thanks for the heads up! we'll investigate doing this another way. we have very light needs for our "html parsing", so the whole `NSHtmlTextDocumentType` machinery was a bit overhanded anyway.

Thanks!
