### ISSUE TITLE
Icorrect screen sizes in TraitController?

### ISSUE THREAD

**Issue by vIiRuS** [kickstarter/ios-oss#29]
While looking through the code, I noticed that the TraitController class seems to have the wrong screen sizes for the 4" and 5.5" iPhones.

The height for 4" is 575, when it should be 568.
The size for 5.5" is 540x960, when it should be 414x736.

Is this maybe intentional, that some of the sizes differ from the actual screen size, or were they entered wrong?

**Comment by mbrandonw** [comment]
oh jeez, oops! you're totally right.

well, if yer interested in it, you could open a PR to correct that! it would require generating new test screenshots (in case there are differences), but that should be easy enough to do.

do you have any interest in that? if not we'll look into it soon!

**Comment by justinswart** [comment]
Fixed in #93
