### ISSUE TITLE
Why RewardPledgeViewModel can initial property stripeTokenAndErrorProperty like this?

### ISSUE THREAD

**Issue by blackchena** [kickstarter/ios-oss#291]
```
fileprivate let stripeTokenAndErrorProperty = MutableProperty(String?.none, Error?.none)

```
MutableProperty has not the initial method, is it means
```
MutableProperty((String?.none, Error?.none))
```

**Comment by justinswart** [comment]
Hi @blackchena, yes - it's not so clear from the syntax but it initializes the `MutableProperty` with a tuple type of `(String?, Error?)`:

<img width="812" alt="screen shot 2018-01-02 at 16 57 24" src="https://user-images.githubusercontent.com/3735375/34506038-3652a2b8-efde-11e7-9f9b-b830c47e74b0.png">

**Comment by blackchena** [comment]
Is this swift's syntax feature?,I have not seen it before
