### ISSUE TITLE
How to write bindViewModel in swift4.0

### ISSUE THREAD

**Issue by PeterLYY** [kickstarter/ios-oss#296]
Declarations from extensions cannot be overridden yet in Swift4.

**Comment by justinswart** [comment]
We (unfortunately) have to do this through swizzling:

https://github.com/kickstarter/ios-oss/blob/master/Kickstarter-iOS/AppDelegate.swift#L33

**Comment by PeterLYY** [comment]
The swizzle method is good.
However, subclasses of UIViewController can not override bindViewModel in Swift4.

[https://github.com/kickstarter/ios-oss/blob/master/Library/UIViewController-Preparation.swift](url)
