### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by heyken** [kickstarter/ios-oss#30]
Hi there, while build project, I detected build error,
I attached some log,
check please..

Hope great Kickstarter!!

<unknown>:0: error: no such file or directory: '/Users/leesanggyu/Documents/Project/kickstarter_heyken/Frameworks/ios-ksapi/Frameworks/native-secrets/ios/Secrets.swift'
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

**Comment by huangwei4478** [comment]
make sure you are using Xcode 7.3.1 on master branch. then you 'make bootstrap' first, ignore the error of unfound Secrets.swift. Finally you would like to 'make test-all' as instructed by the readme.md -- 'make test-all' will find a way to copy Secret.swift back to its position thus make the compile possible. #13

**Comment by heyken** [comment]
Thank you! I got it
