### ISSUE TITLE
About UI Test on CI environment.

### ISSUE THREAD

**Issue by Noodlekim** [kickstarter/ios-oss#307]
Hello.
We are referring to your iOS source when we adjusted MVVM architecture in our project.
ViewModel and DataSource were applied and these are working good.
But UI Test has been failed in Travis-CI environment.
(Interestingly our UI Test is successful in a local.)
Of course there is also a comparison image in the `ReferenceImages_64` folder on GitHub's repository.

If KickStarter had been had issue a similar issue, advice for us please.

**Test code**
```
This is our source code for UI Test.
        [Device.phone4inch, Device.phone4_7inch, Device.phone5_5inch].forEach { (device) in
            withMock(with: MockService.init(userResponse: mockUser), body: {
                let vc = ProfileTableViewController.instantiate()
                let (parent, _) = traitControllers(device: device, orientation: .portrait, child: vc)
                FBSnapshotVerifyView(parent.view, identifier: "\(device)")
            })
        }
```

**Error message in CI**
```
  test_viewcontroller_screenshot, failed - Snapshot comparison failed: Optional(Error Domain=FBSnapshotTestControllerErrorDomain Code=4 "Images different" UserInfo={NSLocalizedFailureReason=image pixels differed by more than 0.00% from the reference image, FBDiffedImageKey=<UIImage: 0x7fe2862caf70> size {414, 736} orientation 0 scale 2.000000, FBReferenceImageKey=<UIImage: 0x7fe2862c5df0> size {414, 736} orientation 0 scale 2.000000, FBCapturedImageKey=<UIImage: 0x7fe28634d0b0> size {414, 736} orientation 0 scale 2.000000, NSLocalizedDescription=Images different})
```

**Comment by justinswart** [comment]
Hey @Noodlekim, snapshot tests can be quite sensitive and you may have failures if the reference and comparison images vary by as much as 1 pixel (depending on the tolerance level set for your test). The following things can typically cause this:

- The simulator that you've recorded the reference snapshots with differs from the version on your CI (Make sure they're exactly the same).
- The versions of Xcode differ.
- The snapshot testing library versions differ.
- There could be layout inconsistencies, if there are issues with auto layout constraints that are possibly ambiguous then those views can render unpredictably and screenshots may arbitrarily fail.

So as well as eliminating the above causes, also ensure that you are using the latest version of `iOSSnapshotTestCase` which is now maintained over at https://github.com/uber/ios-snapshot-test-case.

Hope that helps! 👍

**Comment by Scollaco** [comment]
Hello @Noodlekim,

Actually this happened when the ViewController snapshot differs from the reference image (in your case, ProfileTableViewController). Did you make any change on this screen (changed color, subviews, font, etc)? I suggest you to re-generate a new snapshot by adding `self.recordMode = true` on the `setup()` function of your test class. (Don't forget to delete this line after recording the new snapshot). After generating the new image, push to remote and the test should pass in Travis-CI environment. Let me know if the problem persist.

**Comment by Noodlekim** [comment]
Thank you @justinswart.😃
We will try as your advice.
