### ISSUE TITLE
Any issues with AppEnvironment.current not being Observable?

### ISSUE THREAD

**Issue by eliotfowler** [kickstarter/ios-oss#308]
I notice that the current `AppEnvironment`, which contains the current user, the api service, some tracking information is not observable and I'm curious if that has presented any issues. It seems like you make use of [NotificationCenter notifications for the user switching](https://github.com/kickstarter/ios-oss/blob/master/Kickstarter-iOS/Views/Controllers/RootTabBarViewController.swift#L14-L30) (or session ending) which perhaps handles updating necessary values specific to the user.

If the AppEnvironment.current is replaced due to a user switching or logging in, how do you make sure the views react to it accordingly? Specifically, in the [BackerViewController](https://github.com/kickstarter/ios-oss/blob/master/Library/ViewModels/BackingViewModel.swift#L91), if the current app environment (and subsequently the current user) changes after `viewDidLoad` is called, would the view continue to show the data for the previous current user?

Additionally, if this is handled by the NotificationCenter notifications elsewhere, is the need to observe changes to the AppEnvironment unnecessary given the way the app works (if, for example, user logging in only happens in an isolated part of the app and you know there will be no long-standing view controllers that need to listen for changes to that).

**Comment by justinswart** [comment]
Hi @eliotfowler, it's better to think of the `AppEnvironment` as a simple struct that allows us to easily manage dependency injection for unit tests. It's not something that we use for state (although we sort of can). If we were to attach a `Signal` to the `Environment` then if it was replaced (say by logging in/out) then the `Signal` would also be disposed of course.

One could consider other approaches similar to Redux in which one combines the reducer pattern with some kind of `Signal`/`Observable` but this hasn't been a requirement for us yet and, as you pointed out, the way that we respond to current user switching is through `NotificationCenter`.

If there are long-standing view controllers that need to react to user switching then we handle that within their respective view models.

Hope that helps.

**Comment by eliotfowler** [comment]
Awesome, thanks for the info!
