### ISSUE TITLE
404 error - looks like native-secrets no longer available

### ISSUE THREAD

**Issue by j450h1** [kickstarter/ios-oss#31]
output from  `make test-all`

git clone https://github.com/kickstarter/native-secrets Frameworks/ios-ksapi/Frameworks/native-secrets
Cloning into 'Frameworks/ios-ksapi/Frameworks/native-secrets'...
remote: Repository not found.
fatal: repository 'https://github.com/kickstarter/native-secrets/' not found
make[1]: [secrets] Error 128 (ignored)
if [ ! -d Frameworks/ios-ksapi/Frameworks/native-secrets ]; \
	then \
		mkdir -p Frameworks/ios-ksapi/Frameworks/native-secrets/ios \
		&& cp -n Configs/Secrets.swift.example Frameworks/ios-ksapi/Frameworks/native-secrets/ios/Secrets.swift \
		|| true; \
	fi
xcodebuild test -scheme Kickstarter-Framework-iOS -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' 
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:iOS Simulator, OS:9.3, name:iPhone 6 }

	The requested device could not be found because no available devices matched the request.

	Available destinations for the "Kickstarter-Framework-iOS" scheme:
		{ platform:iOS Simulator, id:A64A1C8E-8CF6-4034-9D5D-8015FE315B88, OS:10.2, name:iPad Air }
		{ platform:iOS Simulator, id:08D76504-6C4C-40BE-8A77-0A91E651E364, OS:10.2, name:iPad Air 2 }
		{ platform:iOS Simulator, id:3B625A32-BFFF-47F7-A050-8830AB66678C, OS:10.2, name:iPad Pro (9.7 inch) }
		{ platform:iOS Simulator, id:CF9411AA-6A47-4AF9-AC0E-50E6249745E2, OS:10.2, name:iPad Pro (12.9 inch) }
		{ platform:iOS Simulator, id:FB771706-E415-4BCE-8268-CF9830424BB4, OS:10.2, name:iPad Retina }
		{ platform:iOS Simulator, id:E55D6180-D535-4495-A515-CB1572823996, OS:10.2, name:iPhone 5 }
		{ platform:iOS Simulator, id:539BD7CE-725B-4022-B632-15589028DA8C, OS:10.2, name:iPhone 5s }
		{ platform:iOS Simulator, id:6836D9A2-188C-49A3-91B7-B288158B92BC, OS:10.2, name:iPhone 6 }
		{ platform:iOS Simulator, id:37FD242D-910B-4C06-B66D-7FD6473FB08A, OS:10.2, name:iPhone 6 Plus }
		{ platform:iOS Simulator, id:9251A038-47F8-45ED-B806-EECCE8059409, OS:10.2, name:iPhone 6s }
		{ platform:iOS Simulator, id:097FE47F-E23A-438B-8DF5-88EC4EAADB7A, OS:10.2, name:iPhone 6s Plus }
		{ platform:iOS Simulator, id:A9146875-7C3C-44FE-A142-FE728162A1C4, OS:10.2, name:iPhone 7 }
		{ platform:iOS Simulator, id:564D152F-FA64-4DCA-8A3F-DB14C45DEAAA, OS:10.2, name:iPhone 7 Plus }
		{ platform:iOS Simulator, id:6935EC5F-6099-4DCA-AC16-E0AB76F6F59A, OS:10.2, name:iPhone SE }

	Ineligible destinations for the "Kickstarter-Framework-iOS" scheme:
		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Generic iOS Device }
		{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Generic iOS Simulator Device }
make[1]: *** [test] Error 70
make: *** [test-all] Error 2

**Comment by mbrandonw** [comment]
It seems this error is because you are running xcode 8+, whereas currently we only support xcode 7.3.x and swift 2.2. 

We are working on our Swift 3 upgrade now (more [here](https://github.com/kickstarter/ios-oss/pull/26)), but in the meantime you unfortunately need to run an older version of xcode :(

**Comment by j450h1** [comment]
Thanks, that explains it. I can wait for the upgrade.
