### ISSUE TITLE
Question about holding a stack of environments

### ISSUE THREAD

**Issue by leojkwan** [kickstarter/ios-oss#328]
Thank you for open sourcing your kickstarter and iOS codebase, it's been really helpful!

I have a quick question about the dependency injection architecture around AppEnvironment and Environment's on iOS. Why does the application need to hold a stack of environments? I suspect it may have to do with running concurrent tests that require separate environments, but I'd love to get a bit more insight on the decision to hold a stack of environments instead of just a static `current` environment.

**Comment by Scollaco** [comment]
@leojkwan You are right. We hold a stack to run tests that require separate environments. This was a decision of the team of engineers that used to work here, but the usage of a static environment would be perfectly fine.

**Comment by leojkwan** [comment]
Thanks for the clarification!

**Comment by Scollaco** [comment]
Glad I could help! 👍
