### ISSUE TITLE
Playgrounds do not work

### ISSUE THREAD

**Issue by tomassliz** [kickstarter/ios-oss#336]
I tried to run playgrounds in your project but it does not seem that any of them is running without an error. I have Xcode Version 9.3 (9E145). I followed all steps like 'make bootstrap' etc. A lots of errors is caused inside the `initialize()` function. Do you know about this issue? Or am I doing something wrong?

Here is the error directly from Playgrounds:

![screen shot 2018-04-23 at 14 35 45](https://user-images.githubusercontent.com/3275022/39126859-c81ee374-4703-11e8-9df6-107693343c8a.png)

**Comment by justinswart** [comment]
This may have been fixed since merging #334 and #335 🤔

**Comment by amadeu01** [comment]
I'm facing the same issue 😢

**Comment by amadeu01** [comment]
@justinswart in my PR I just fixed the methods headers. But, still, I had some problems with playground. On #277 I tried to ask how to run with playground. I got a lot of problems and could not get it working 😭

**Comment by justinswart** [comment]
This isn't something we're actively supporting as we only occasionally use it in our development process. Please PR a fix if you do get it working, closing for now 🙂

**Comment by tomassliz** [comment]
@justinswart Really? I saw some talks with Brandon Williams about Playground driven development in Kickstarter:
https://talk.objc.io/episodes/S01E51-playground-driven-development
https://www.youtube.com/watch?v=DrdxSNG-_DE

So you do not use this approach anymore? And if not, what's the reason?

**Comment by justinswart** [comment]
@tomassliz Brandon has moved on from Kickstarter and the team isn't currently using this approach as much. No real reason, we think it's useful, there is of course an amount of maintenance required to keep the Playgrounds functional as you've discovered.
