### ISSUE TITLE
Production Configuration 

### ISSUE THREAD

**Issue by embassem** [kickstarter/ios-oss#421]
it's a Question not an issues 
 how  do you manage production configuration to not be included in the  repo and  to be  available  with your team  ?

**Comment by justinswart** [comment]
Hi @embassem, [this line](https://github.com/kickstarter/ios-oss/blob/master/Makefile#L132) of our `Makefile` is relevant. We synchronize a submodule repo containing our `Secrets.swift` file. Only our private CI and our team has access to this repo so when it runs on our OSS repo it replaces this file with a template.

**Comment by embassem** [comment]
thanks for clarification
