### ISSUE TITLE
How to run bootstrap?

### ISSUE THREAD

**Issue by louisnewman** [kickstarter/ios-oss#43]
I cloned the source code and run the program,but Xcode told me the “KSapi” is missing,I don’t know why, and I run bootstrap ,the terminal issued me no sucn directory,I’m a fish,fresh fish,Please help me.Thanks

**Comment by mbrandonw** [comment]
`KsApi` is a submodule and so requires initialization. Running `bootstrap` does that and so you should be able to compile after bootstrapping.

**Comment by mbrandonw** [comment]
Im going to close this for now, but let us know if you have other problems!
