### ISSUE TITLE
Setup project

### ISSUE THREAD

**Issue by awessoEsso** [kickstarter/ios-oss#446]
For learning purposes i tried cloning project but i can't build it. 
After doing "make bootstrap" some dependencies still missing

**Comment by ifbarrera** [comment]
Hi @awessoEsso, thanks for reporting this issue you're seeing. Can you describe what build error you're getting, or what dependencies are still missing after running `make bootstrap`?

**Comment by awessoEsso** [comment]
Thanks @ifbarrera 
This are dependencies missing
![image](https://user-images.githubusercontent.com/6775901/46957306-9304bb00-d097-11e8-91b3-9201db7c3daf.png)

**Comment by awessoEsso** [comment]
I added $(PROJECT_DIR) in Framework Search Paths and it works.
Thanks you all for your help

**Comment by jitendragaur** [comment]
I am also not able to build the project getting missing module (Prelude, Argo)

![screen shot 2018-10-18 at 9 16 36 pm](https://user-images.githubusercontent.com/2297508/47167150-72e52e00-d31b-11e8-8a8b-32b2b3f7be6a.jpg)
