### ISSUE TITLE
Kickstarter-iOS requires a provisioning profile

### ISSUE THREAD

**Issue by iitjee** [kickstarter/ios-oss#48]
I get the following error when I try to run: ('Automatically signing project' is unchecked)
![screen shot 2017-01-17 at 7 49 09 pm](https://cloud.githubusercontent.com/assets/20602254/22022931/0872ba98-dcea-11e6-8d6c-73a3ebcfe8a0.png)
 
and I get `Your account does not have sufficient permissions to modify containers.` and `No profiles for 'com.MYDOMAINNAME.kickstarter.alpha' were found` when I checkmark 'Automatically signing project'

Please help!

**Comment by mbrandonw** [comment]
Hi! Sorry we have been having trouble with automatic signing of our builds so we disabled it. feel free to turn on automatic for your local repo and see if it works for you.

**Comment by iitjee** [comment]
Hi
 I get Your account does not have sufficient permissions to modify containers. and No profiles for 'com.MYDOMAINNAME.kickstarter.alpha' were found when I turned on 'Automatically signing project'

**Comment by mbrandonw** [comment]
you might have to change the development team?

**Comment by iitjee** [comment]
Yes, I've changed to that of mine viz MYNAME(Personal Team).

**Comment by mbrandonw** [comment]
Sorry I'm not sure then. I can't think of anything that would cause that. Seems like it should be possible to clear the provisioning/code signing settings of anything referring to our info.

**Comment by iitjee** [comment]
![screen shot 2017-01-17 at 7 51 18 pm](https://cloud.githubusercontent.com/assets/20602254/22023394/fea21f5c-dceb-11e6-8700-8bdb2ddba4ac.png)
Tried that. Still getting the same unfortunately!

**Comment by pahnev** [comment]
@iitjee you might need to be signed for the paid dev program. I tried this with my personal account and had the error  `The 'iCloud' feature is only available to users enrolled in Apple Developer Program. Please visit `
Once I switched the team that is a paid account, it signed it just fine.
