### ISSUE TITLE
There's no information or feedback on a poor connection or no connection.

### ISSUE THREAD

**Issue by jjcastro** [kickstarter/ios-oss#487]
*(First of all thanks for open sourcing the app! This has been a great resource for wrapping my head around reactive programming on iOS)* Here's a bug report / UI quirk I found that could be improved :)

There's no feedback or useful error messages when the app is no longer connected to the internet or when it's on a poor connection. Here's some specifics:

- On some views like **Project Comments** or the **Activity tab**, the controller is completely empty. 
- On some links/buttons, the message is only "Something went wrong" or in the Spanish version, the even less helpful "Something happened here".
- Projects can still be saved, and the navigation bar button icon still turns red, as though confirming the project has been saved successfully. However, it does not work, as soon as the user is back on a good connection the project is not saved and the button icon is back to the light version.

## Steps

This is running on an iPhone XS Max on iOS 12.1. App version is 3.9.11.

- Use the app to see some projects and some videos.
- Turn on Airplane Mode or connect to a poor Wi-Fi.
- Continue using the app for the use cases above.

## Expected behavior

- The app should inform the user about the lack of internet connection.
- The app should not allow the user to perform internet-dependent actions like saving a project, less of play the UI feedback to confirm the action took place succesfully.
- The app should not completely empty controller, instead informing something along the lines of "There's nothing here" or "Connect to the internet to see comments, etc"

![img_3242](https://user-images.githubusercontent.com/9254507/48789389-e7184600-ecba-11e8-9200-1e502b05bd74.PNG)
![img_3243](https://user-images.githubusercontent.com/9254507/48789392-e97aa000-ecba-11e8-8e5a-1b164a80f441.PNG)
![img_3169](https://user-images.githubusercontent.com/9254507/48789395-eb446380-ecba-11e8-8b79-51e33aa55157.PNG)

**Comment by justinswart** [comment]
@jjcastro Thanks for the feedback! This is actually on our roadmap to implement in the near future, I'll comment here once it's merged 👍

**Comment by justinswart** [comment]
@jjcastro gonna close this for now, sorry I'm not sure exactly when it'll be implemented but when it is you'll be the first to know! 😅
