### ISSUE TITLE
Bootstrapping fails because of native-secrets

### ISSUE THREAD

**Issue by yas375** [kickstarter/ios-oss#7]
First of all: congrats on open sourcing the mobile apps 👏  Thanks for doing so!

I'd like to explore the code and have tried to set it up on my machine. But `make bootstrap` fails. Probably because https://github.com/kickstarter/native-secrets.git is available for Kickstarter employees only. Maybe the bootstrap script can be modified to allow people outside of Kickstarter to setup and then build & run the app locally? Thanks in advance.

```
➜  kickstarter git:(master)  make bootstrap
...
Cloning into '/Users/yas/code/kickstarter/Frameworks/ios-ksapi/Frameworks/Curry'...
Cloning into '/Users/yas/code/kickstarter/Frameworks/ios-ksapi/Frameworks/Prelude'...
Cloning into '/Users/yas/code/kickstarter/Frameworks/ios-ksapi/Frameworks/ReactiveExtensions'...
Cloning into '/Users/yas/code/kickstarter/Frameworks/ios-ksapi/Frameworks/native-secrets'...
Username for 'https://github.com':
```

**Comment by stephencelis** [comment]
Sorry about that! We're still figuring out how to manage private resources. Hope to get this fixed shortly via #8.
