### ISSUE TITLE
make bootstrap error

### ISSUE THREAD

**Issue by StoneCX** [kickstarter/ios-oss#75]
Xcode is 8.2.1 and i'm clone it  execute "make bootstrap"then always error and i don't know why
`curl -s -N -L https://tokbox.com/downloads/opentok-ios-sdk-2.10.0 \
		| tar -xz --strip 1 --directory Frameworks/OpenTok OpenTok-iOS-2.10.0/OpenTok.framework
tar: Error opening archive: (Empty error message)
make: *** [opentok] Error 1`

**Comment by justinswart** [comment]
Hi @StoneCX, I'm not sure why that's happening, perhaps it's failing to download the OpenTok library's tar ball. We use this library for live streaming.

You can work around this by doing the following:
1. Comment out the `opentok` recipe steps in `Makefile` (lines 108 - 110).
1. Download OpenTok manually [here](https://tokbox.com/downloads/opentok-ios-sdk-2.10.0).
1. Extract `OpenTok.framework` from the archive to `{PROJECT_DIR}/Frameworks/OpenTok/`.
1. Run `make bootstrap` again.

**Comment by StoneCX** [comment]
@justinswart thanks that's work

**Comment by waseefakhtar** [comment]
Sorry I don’t know which lines are the `opentok` recipe steps. I comment out 108 - 110 like:

```
VERSION_FILE = Frameworks/OpenTok/version
CURRENT_OPENTOK_VERSION = $(shell cat $(VERSION_FILE))
ifeq ($(CURRENT_OPENTOK_VERSION),)
```

And I get `Makefile:112: *** extraneous `endif'.  Stop.`. When I include endif with the commenting out (108 - 112) like:

```
VERSION_FILE = Frameworks/OpenTok/version
CURRENT_OPENTOK_VERSION = $(shell cat $(VERSION_FILE))
ifeq ($(CURRENT_OPENTOK_VERSION),)
	CURRENT_OPENTOK_VERSION = first
endif
```

I get `make: *** No rule to make target `bootsrap'.  Stop.`

Am I commenting out the wrong lines?

**Comment by justinswart** [comment]
@waseefakhtar are you sure you're typing `make bootstrap`? the error you've pasted has the incorrect spelling.
