### ISSUE TITLE
Instructions for Using Playgrounds in Project

### ISSUE THREAD

**Issue by timcamber** [kickstarter/ios-oss#9]
It's very exciting to take a look through this project; thanks for open-sourcing it!

Maybe this is a dumb question, but for whatever reason I haven't seen much of the playground-embedded-in-project-with-required-modules style, and I'm having some trouble using the many playgrounds in the project. I feel like I should be able to figure this out, but I haven't.

Maybe some brief instructions could be included describing how to get playgrounds within the project running?

(Basically, I get "No such module 'Module Name'" in the playgrounds that import an included module)

**Comment by mbrandonw** [comment]
@timcamber thanks for the heads up! we're fixing an issue with the dependencies and then everything should work!

**Comment by mbrandonw** [comment]
@timcamber can you try cloning again and do a build of the main app target, and then try the playground?

if that doesnt work I'll hone in on better instructions...

**Comment by txlaijava** [comment]
感谢开源

**Comment by timcamber** [comment]
Still not working for me, but maybe I'm missing something obvious. These are the steps I'm taking:

• Clone the repository
• Navigate to location of cloned repo, `make bootstrap` in that directory
• Open `Kickstarter.xcodeproj` in Xcode 7.3.1
• Build to a simulator with `Kickstarter-iOS` scheme (`⌘-B`)
• Navigate (using the `Kickstarter.xcodeproj` project in Xcode, still open) to any playground page in `Kickstarter-ios.playground` or any of the playgrounds inside `Frameworks/[A-Framework].xcodeproj/`

In any of these places, I seem to see "No such module '[Module-Name]'", where the module is one of the many frameworks included in the project.

Let me know if I can do anything else to help track this down. Thanks!

(Doing all this from `master` as of right now, commit `66087aa`)

**Comment by mfclarke** [comment]
@timcamber I managed to get it to work by building Kickstarter-Framework-iOS first (for sim). 

Remember to activate the assistant editor and choose the "Timeline" option

**Comment by timcamber** [comment]
@mfclarke thanks for the suggestion. Unfortunately that's not working for me. Add to my steps above:

• Select `Kickstarter-Framework-iOS` from the scheme selector, and build
• After building, navigate to any playground page and attempt to run the playground.

I still see, "No such module 'KsApi'", e.g., or any other module that's imported at the top of a playground.

**Comment by timcamber** [comment]
[This issue](https://github.com/kickstarter/ios-oss/issues/12) just gave me an idea: is it an issue that my `Xcode.app` in `/Applications/` is Xcode 8.x, and that Xcode 7.3.1 is a separate app (named `Xcode_7.3.1.app`) while I run `make bootstrap`?

**Comment by stephencelis** [comment]
@timcamber That could definitely be an issue! You can temporarily use `xcode-select` to use that version:

```
sudo xcode-select -s path/to/Xcode_7.3.1.app/Contents/Developer 
```

**Comment by timcamber** [comment]
@stephencelis Progress!

Still having an issue. After switching to the older version of Xcode, `make bootstrap` ends up giving me an error:

`Error: Your Xcode (7.3.1) is too outdated.`

Not sure which step is emitting that error.

**Comment by stephencelis** [comment]
@timcamber Actually, re-reading your comment makes me think my `xcode-select` suggestion won't help there. Did **Kickstarter-Framework-iOS** previously build just fine from Xcode 7.3.1? Sometimes playgrounds don't see build artifacts after a first build, but quitting/reopening Xcode has helped me in the past here.

**Comment by timcamber** [comment]
@stephencelis 

`Kickstarter-Framework-iOS` builds fine (to Simulator target) in Xcode 7.3.1 (7D1014). When I try to execute a playground (within `Kickstarter.xcodeproj`, I get the "No such module" errors. Quitting / reopening Xcode didn't help.

Here's a video in case I'm mis-representing any of my steps:

https://dl.dropboxusercontent.com/u/1991225/Kickstarter.mov

**Comment by marcusficner** [comment]
At first I also couldn't get it to work. Additionally to the "No such module 'KsApi" error, which was resolved after building __Kickstarter-Framework-iOS__ Xcode displayed the message "Unable to find execution service for selected run destination". 
I've __xcode-select__ed back to Xcode 7, because I'm using Xcode 8 as the default one and reseted the simulators. Then everything worked as expected.

**Comment by stephencelis** [comment]
@timcamber We're a bit stumped on this one, sorry! 😞 Can you try the suggestions above and see if that gets things running? Could very well be something to do with old build products, simulator data, etc.

**Comment by timcamber** [comment]
@marcusficner @stephencelis are you all getting everything to work on macOS Sierra 10.12.x, and with Xcode 8.x installed alongside Xcode 7.3.1? 

The last thing I can think of is that `make bootstrap` doesn't fully succeed (in the steps involving `homebrew`) while command line dev tools are Xcode 7.3.1. I've therefore been using Xcode 8.x command line tools to run `make bootstrap`, and using Xcode 7.3.1 thereafter.

Unfortunately, quitting/restarting Xcode or resetting simulators doesn't seem to do the trick.

I'm also happy to investigate further if you have any ideas (project settings search paths? Look for the module build products somewhere?)

**Comment by timcamber** [comment]
Wow! Found a solution.

I just had to make sure an iPad Pro was in my list of simulator devices. 

(Perhaps atypically, I had cleaned up my list of simulators so ones I didn't use frequently weren't polluting the list)

Maybe under the hood playgrounds run inside an iPad Pro simulator?

Thanks to http://stackoverflow.com/a/33461378/1148702 for the solution.
