### ISSUE TITLE
This is not a issue, Just a problem

### ISSUE THREAD

**Issue by yangzhuoli** [kickstarter/ios-oss#927]
This is an awesome project, It use a lot of functional programming knowledge, that's awesome!!

what make me confuse is ,why use functional programming, can make it clear? or make it easy ? or save time?

Can you explain it? thank you very much

**Comment by justinswart** [comment]
Hey there - a good resource for why one would use functional programming is our friends over at @pointfreeco, check out their really great videos here: https://www.pointfree.co/

Here's a good one to start with: https://www.pointfree.co/episodes/ep1-functions

The paradigms and style of programming in FP may seem strange at first, but over time they'll seem even stranger except you'll just learn to live with it.

Just kidding, watch the videos.
