### ISSUE TITLE
Show/Hide Password button overridden by orientation change 

### ISSUE THREAD

**Issue by robjaq** [kickstarter/ios-oss#949]
System: 12.4
Device: iPhone X
Version: 3.20.1
Steps: Type into password field > tap eye icon to unhide > rotate > password field autohides > then you have to double tap the icon to show again

![pic1](https://user-images.githubusercontent.com/30357661/68901987-f6727980-06eb-11ea-8d61-ac74b6a26068.gif)

I would like to submit a pr if that's cool. This project is pretty dope =D
![pic2](https://user-images.githubusercontent.com/30357661/68902170-6e40a400-06ec-11ea-9e7a-168bd461cc83.gif)

**Comment by justinswart** [comment]
hey @robjaq thanks for letting us know and for digging into it! I believe you've spoken to @ifbarrera about this separately - feel free to open a PR from a fork, our tests should run on it and we'll review your PR to help you get it merged 👍

**Comment by justinswart** [comment]
Thanks! Closing this for now, we can track is on the PR that you opened.
