### ISSUE TITLE
tar: OpenTok-iOS-2.10.0/OpenTok.framework: Not found in archive

### ISSUE THREAD

**Issue by ludaye123** [kickstarter/ios-oss#95]
tar: OpenTok-iOS-2.10.0/OpenTok.framework: Not found in archive
tar: Error exit delayed from previous errors.

**Comment by justinswart** [comment]
Hey @ludaye123 this seems to sometimes happen when the OpenTok binary download fails, there's a command in the Makefile that downloads it and then pipes it through for extraction but if the download fails or is incomplete then it gives these sort of nondescript errors. I'll take a look at improving this when I can but for now please try following the steps I mentioned in a previous issue:

https://github.com/kickstarter/ios-oss/issues/75

**Comment by ludaye123** [comment]
Yeah, awesome, that's work
