### ISSUE TITLE
Downloading OpenTok v2.10.0 tar: OpenTok-iOS-2.10.0/OpenTok.framework: Not found in archive tar: Error exit delayed from previous errors.

### ISSUE THREAD

**Issue by cstars135** [kickstarter/ios-oss#97]
I run "make  bootstrap", then I get above error. Next,I run "make test-all", I get this--"Testing failed: No such module 'OpenTok'".
![edb34b96-a96a-4e8a-b3c8-51fa7ba170e3](https://cloud.githubusercontent.com/assets/5800672/23117858/ab302786-f78c-11e6-8ba3-c8ec32737600.png)
So I guess there must be something wrong with it. I download it again from it's website.  Unzip it by "tar -jxvf  OpenTok-iOS-2.10.1.tar.bz2", then show me below results:
![029a1184-6801-4d81-a3c6-18dc5234f8e8](https://cloud.githubusercontent.com/assets/5800672/23117257/cf2ce0a0-f789-11e6-8da6-a43d3b3d8af5.png)
 I ignored these errors and added it into the project, as I expected ,the project can't  compiled。Xcode prompt “no such module 'OpenTok' ”. I have tried to set building setting->searchPath, but it' not work. Finally,I stuck here.
![2b7e3b83-efa3-46b6-8505-0259d9abd3c2](https://cloud.githubusercontent.com/assets/5800672/23117342/3c090000-f78a-11e6-9b02-43edb32cbb09.png)

**Comment by justinswart** [comment]
Hey @cstars135. We unfortunately have issues with the OpenTok download failing sometimes. Please follow the steps mentioned here for now: #75 and see if that helps.

**Comment by cstars135** [comment]
Thank you for your rapid responses!
