### ISSUE TITLE
Stop support iOS 8?

### ISSUE THREAD

**Issue by hprobotic** [kickstarter/ios-oss#98]
I saw in deployment target is minimum 9.0. Are you dropped iOS 8 devices ?. 
And can you give me a extension to use instead Alamofire

**Comment by mbrandonw** [comment]
> I saw in deployment target is minimum 9.0. Are you dropped iOS 8 devices ?.

yeah we have.

> And can you give me a extension to use instead Alamofire

not sure i understand. can you clarify a bit?

**Comment by hprobotic** [comment]
@mbrandonw  Our company is migrating to swift 3. But a lot of our user still use iOS 8 devices. As i know. Alamofire is dropped iOS 8 also. 
What is extension should use instead Alamofire?
