### ISSUE TITLE
I'm having an issue when I try to make bootstrap

### ISSUE THREAD

**Issue by Aioria1314** [kickstarter/ios-oss#986]
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/username/SourceTree/ios-oss/Carthage/Checkouts/Kickstarter-ReactiveExtensions/ReactiveExtensions.xcodeproj -scheme ReactiveExtensions-iOS -configuration Release -derivedDataPath /Users/username/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B500/Kickstarter-ReactiveExtensions/c3ce269fd2dd14b8d63ce1bc5b78f7397c0c0753 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/jh/d1w9zthn497fcvz9ytqq1rjr0000gn/T/Kickstarter-ReactiveExtensions SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/username/SourceTree/ios-oss/Carthage/Checkouts/Kickstarter-ReactiveExtensions)

**Comment by evgenbakumenko** [comment]
same :(

**Comment by justinswart** [comment]
Please use Xcode 10.3 for now, we haven't had time to update the project to compile with Xcode 11 yet.

**Comment by Aioria1314** [comment]
> Please use Xcode 10.3 for now, we haven't had time to update the project to compile with Xcode 11 yet.

Thx :)
